-- How create a big string of bytes?
-- Using \z makes Lua ignore the new line and the indentation, example:
-- local s = "\a\a\a\a\a\a\a\a\a\a\a\a\z
--              \a\a\a\a\a\a\a\a\a\a\z
--              \a\a\a"
